### ISSUE TITLE
Autoneg controller can block deletion of a Service and even of the namespace containing it.

### ISSUE THREAD

**Issue by bert-laverman** [GoogleCloudPlatform/gke-autoneg-controller#10]
Reproduce: Create a service with a backend name that conatins an udnerscore. Now try to clean up. Eventually I tried to delete the entire namespace, but that is waiting on the deletion of the Service, which cannot proceed even though there is nothing to cleanup.

**Comment by morgante** [comment]
FYI you can use this command to bail out by removing the finalizer. Then you can delete the service:

```
kubectl get service $SERVICE_NAME -o=json | \
  jq '.metadata.finalizers = null' | kubectl apply -f -
```

**Comment by bert-laverman** [comment]
I actually managed to do this through the console by editing the state and removing the hook.
