### ISSUE TITLE
Autoneg does not provide default configuration for max-rate-per-endpoint and max-connections-per-endpoint

### ISSUE THREAD

**Issue by agh95** [GoogleCloudPlatform/gke-autoneg-controller#104]
Autoneg requires setting `max-rate-per-endpoint`/`max-connection-per-endpoint` in the annotations. This property is a bit complex to understand and get right so as an infrastructure team we would like to abstract our users away from it. One way to do that is if autoneg provided config option to set default value for this setting.

**Comment by rosmo** [comment]
Having the defaults is fine, though I think it might prove to be quite difficult to set good defaults (as every application's traffic tolerance is different).
