### ISSUE TITLE
ReconcileBackends succeeds although some operations fail

### ISSUE THREAD

**Issue by fbaier-fn** [GoogleCloudPlatform/gke-autoneg-controller#11]
We ran into an issue that the autoneg controller reports backends being added to NEGs although some patch operations fail with `RESOURCE_NOT_READY`. 

It seems that applying patches to reconcile backends is handled optimistically, leading to a wrong reconciliation result.

For now I applied a workaround by retrying the patch in such case. See https://github.com/fbaier-fn/gke-autoneg-controller/commit/225576de9fa90a6872e152fe33f042f13b31241c which I would be more than happy to contribute my fix.

**Comment by rwkarg** [comment]
Assuming that _something_ could cause even those 5 attempts to not be successful, should there be a process to periodically reconcile the service (and it's annotation) with the actual state of the backend?

**Comment by soellman** [comment]
I'll close this issue since we've merged the PR.

Discussion of a longer-term reconcile can continue in #7
