### ISSUE TITLE
Do you have plans for create Helm Chart for Autoneg installation?

### ISSUE THREAD

**Issue by ksemele** [GoogleCloudPlatform/gke-autoneg-controller#111]
Hello everyone!
Do you have plans for create Helm Chart for Autoneg installation?
I think that Deployment raw manifest with `latest` tag it's not a best option for managing gke-autoneg-controller.

**Comment by movergan** [comment]
Agree! Managing AutoNEG as part of IaC via flux or argO would be great! Now we keep a copy of the manifest and update it manually from time to time.

**Comment by rosmo** [comment]
I would be very happy to accept a PR for a Helm Chart :)

**Comment by ksemele** [comment]
@rosmo well... feel free to review my PR: https://github.com/GoogleCloudPlatform/gke-autoneg-controller/pull/115 :)
