### ISSUE TITLE
NEGs not getting deregistered on removing autoneg annotation

### ISSUE THREAD

**Issue by akshaypatidar1999** [GoogleCloudPlatform/gke-autoneg-controller#139]
### Description

The controller does not remove NEGs from backend service on removing `autoneg` annotation

### Problem
The issue is this [line](https://github.com/GoogleCloudPlatform/gke-autoneg-controller/blob/master/controllers/service_controller.go#L82), the `getStatuses` method returns `false` if `controller.autoneg.dev/neg` annotation is not found and the controller skips this event. Ideally the `getStatuses` method should return true if `controller.autoneg.dev/neg-status` is found.

### How to reproduce

- Create a service and added  `controller.autoneg.dev/neg` annotation along with `cloud.google.com/neg`, the controller will then successfully register the NEGs to the backend service and add `controller.autoneg.dev/neg-status` annotation
- Remove `controller.autoneg.dev/neg` from the service
- The NEGs will not get deregistered from the backend service

### Contribution

I will be happy to contribute to this issue

**Comment by rosmo** [comment]
Yeah, I think you might be right here. For a workaround, have you tried just adding an empty annotation?

**Comment by akshaypatidar1999** [comment]
Thanks @rosmo the workaround works.
Would be able to review if I raise a PR with the proper fix?

**Comment by rosmo** [comment]
Absolutely, but if you put it behind a feature flag, that would be great. I don't think anyone relies on the current behavior, but at least we could phase it out cleanly in case someone actually does.

**Comment by akshaypatidar1999** [comment]
@rosmo I have raise a PR for fixing this issue https://github.com/GoogleCloudPlatform/gke-autoneg-controller/pull/140. Can you please have a look.
