### ISSUE TITLE
Flaky TestReconcileStatuses because maps don't guarantee order

### ISSUE THREAD

**Issue by fbaier-fn** [GoogleCloudPlatform/gke-autoneg-controller#14]
`make test` fails occasionally for https://github.com/GoogleCloudPlatform/gke-autoneg-controller/blob/master/controllers/autoneg_test.go#L248-L258 because we transform a slice to map then back to a slice (see https://github.com/GoogleCloudPlatform/gke-autoneg-controller/blob/master/controllers/autoneg.go#L141) which can mess up the order assumed in the test https://github.com/GoogleCloudPlatform/gke-autoneg-controller/blob/master/controllers/autoneg_test.go#L157-L170.

So if we compare the returned slice, sometimes the group of `zone2` comes before `zone1` and will have the test fail.

I propose modifying `isEqual` ala:

```
func (b Backends) isEqual(ob Backends) bool {
	if b.name != ob.name {
		return false
	}
	newB := map[string]compute.Backend{}
	for _, be := range b.backends {
		rb := relevantCopy(be)
		if _, ok := newB[rb.Group]; ok {
			return false
		}
		newB[rb.Group] = rb
	}
	newOB := map[string]compute.Backend{}
	for _, be := range ob.backends {
		rb := relevantCopy(be)
		if _, ok := newOB[rb.Group]; ok {
			return false
		}
		newOB[rb.Group] = rb
	}
	return reflect.DeepEqual(newB, newOB)
}
```

**Comment by soellman** [comment]
Fixed by #34
