### ISSUE TITLE
Can't attach NEGs to internal backend services

### ISSUE THREAD

**Issue by fdfzcq** [GoogleCloudPlatform/gke-autoneg-controller#141]
We want to attach NEGs to a backend service used by internal network passthrough LB and fails due to:
`Error 400: Invalid value for field 'resource.backends[0].capacityScaler': '1.00'. Capacity scaler must not be set for an INTERNAL backend service., invalid`

Feature request: allow empty capacityScaler for internal backend services.

**Comment by fdfzcq** [comment]
We found a workaround, will close the issue.

**Comment by rosmo** [comment]
Could you please share your workaround with the larger community? :)

**Comment by fdfzcq** [comment]
Sorry @rosmo just saw the message now! The workaround was ugly, I ended up changing autoneg's code and built and published an internal image of it. We also eventually found another LB alternative that doesn't involve setting up NEGs at all.
