### ISSUE TITLE
GCLB backends are not populated by AutoNEG controller: RESOURCE_NOT_READY

### ISSUE THREAD

**Issue by artazar** [GoogleCloudPlatform/gke-autoneg-controller#18]
Hi,

I am trying to use AutoNEG controller in Workload Identity mode (configured according to the manual), and I face a problem with auto populating the GCLB backends.

I noticed that shortly after creating GKE services, the backends show the NEGs in GC console, but then they disappear and never show up again.

The sequence of events according to Stackdriver logs:
https://pastebin.com/FKdhqYTy

I can see BAD_REQUEST and RESOURCE_NOT_READY errors there.

I have AutoNEG controller working correctly in neighbor projects, but using cloud access scopes. It's just for extra context, I am not sure if this particular issue is related to Workload Identity setup or not.

Inside the affected NEG I can see undefined health status:
![image](https://user-images.githubusercontent.com/19729346/94884426-a59c7880-0497-11eb-8fde-d2395f040aa2.png)

However I think (though not sure) that this is because it is "Not used yet" by the backend, so it's a consequence.

Also the problem persists, even if I remove GKE services and create them again - so it is not any kind of a race with LB backend service creation.

Any idea what goes wrong here?

Also posted: https://serverfault.com/questions/1036096/gclb-backends-are-not-populated-by-autoneg-controller-resource-not-ready

**Comment by artazar** [comment]
The reason was: the workload identity account created for AutoNEG should have compute.networkUser permission in the host project to obtain the name of the network/subnet. This is true for shared VPC environments.

The action item in this issue is to update the documentation accordingly.

**Comment by soellman** [comment]
Fixed, thanks for reporting!
