### ISSUE TITLE
The Dockerfile does not build a working image

### ISSUE THREAD

**Issue by mvanholsteijn** [GoogleCloudPlatform/gke-autoneg-controller#27]
to reproduce, type:

```shell-session
$ git clone git@github.com:GoogleCloudPlatform/gke-autoneg-controller.git
$ cd gke-autoneg-controller
$ docker build -tx .
------
 > [builder 7/9] COPY api/ api/:
------
failed to compute cache key: "/api" not found: not found
```

**Comment by soellman** [comment]
Thanks Mark! I've addressed this in a different way in commit 4e289f9.

I prefer not to touch the Dockerfile where possible, as that is autogenerated by kubebuilder. Instead we just create the api directory when performing `make docker-build`.
