### ISSUE TITLE
Migrate to kubebuilder 3

### ISSUE THREAD

**Issue by soellman** [GoogleCloudPlatform/gke-autoneg-controller#35]
https://book.kubebuilder.io/migration/migration_guide_v2tov3.html

Kubebuilder doesn't have features required for autoneg, but it'd be nice to migrate to v3 to stay current on our dependencies. Migration shouldn't be difficult as autoneg already implements/satisfies some of the changes/requirements in v3.

**Comment by fdfzcq** [comment]
+1 on this, we can't even run tests on m1 because v2 doesn't work with v3.

**Comment by rosmo** [comment]
Just checking this out as it seems to becoming an issue, just rebased the v3 branch.
