### ISSUE TITLE
Removing config annotation does not deregister backends

### ISSUE THREAD

**Issue by soellman** [GoogleCloudPlatform/gke-autoneg-controller#45]
Removing config annotation `anthos.cft.dev/autoneg` still left the `anthos.cft.dev/autoneg-status` annotation, and also generated a `controller.autoneg.dev/neg-status` annotation.

I would expect autoneg to deregister backends, remove the status annotation, and remove the finalizer.

**Comment by rosmo** [comment]
Please check the latest comment in #88.
