### ISSUE TITLE
Terraform configuration unusable for multiple clusters 

### ISSUE THREAD

**Issue by romankor** [GoogleCloudPlatform/gke-autoneg-controller#54]
Right now the controller is installed terraform module that way 
```terraform
module "autoneg" {
  source = "github.com/GoogleCloudPlatform/gke-autoneg-controller//terraform/autoneg"

  project_id = "your-project-id"
}
```
where the only thing configurable is the` project-id` .

It creates a custom role for the controller, so that module is completely unusable when installing it on different clusters in the same project, it will fail cause it just tries to create the same custom role

**Comment by rosmo** [comment]
Hey @romankor,

I suggest you use the individual modules (`terraform/modules/gcp` to create service account and role - as the service account gets project-wide permissions and the Workload Identity namespace is per project, it doesn't make a lot of sense to have separate service accounts for each cluster - but you could do that), `terraform/kubernetes` to set up individual clusters).
