### ISSUE TITLE
Configurable default capacityScaler

### ISSUE THREAD

**Issue by jawnsy** [GoogleCloudPlatform/gke-autoneg-controller#68]
Hello,

Thanks for this excellent project!

At Prefect, we are using this controller to perform traffic splitting and blue/green deployments. As far as I can tell, the default (and hard-coded) behavior of this controller is such that traffic will be immediately load balanced between all participating services once the health checks succeed, and we would instead prefer to gradually shift traffic over by configuring the split ratio.

This seems to be the relevant code: https://github.com/GoogleCloudPlatform/gke-autoneg-controller/blob/64a7216c819cfb0377b0be163bedd94b5b3e31c4/controllers/autoneg.go#L62-L66

Would you accept a PR that adds configurability for the InitialCapacity value? We could store that in the existing AutonegConfig object.

I have two use cases in mind for this feature:

* Bringing up an application and cluster in a new zone/region
* Creating a new cluster for a blue/green deployment

In both cases, we want to gradually shift some traffic to the new cluster and monitor error rates.

With the current behavior, if we use the same connection rate settings for the service, then bringing up a new cluster would take an equal proportion of traffic (e.g. live cluster A processing 100% of requests, bringing up a new cluster B and attaching to the same NEG will result in a 50%/50% split.) We would like to begin with 100%/0% split, gradually increase the proportion of traffic that Cluster B handles, and then gradually decrease the proportion of traffic that Cluster A handles, to safely transition.

**Comment by rosmo** [comment]
I would most certainly accept a PR that adds this support!
