### ISSUE TITLE
Autoneg controller gets confused when Backend Service doesn't exist and example is causing it

### ISSUE THREAD

**Issue by bert-laverman** [GoogleCloudPlatform/gke-autoneg-controller#9]
The example in the README uses a Backend Service with a name containing an underscore. However, it is impossible to create a Backend Service with this name.

As a result nothing happens, but even deleting the Service is no longer possible, because the controller keeps getting stuck on the Backend Service name that is rejected.

**Comment by soellman** [comment]
Closing this as a dupe of #10 - both are due to the same behavior.
