### ISSUE TITLE
Update guide or description of compatibility guarantees

### ISSUE THREAD

**Issue by jawnsy** [GoogleCloudPlatform/gke-autoneg-controller#93]
Pull request https://github.com/GoogleCloudPlatform/gke-autoneg-controller/pull/46 changes some flags, which is a breaking change unless users re-deploy using the Deployment manifest. I'd propose either:

* Adding a warning that breaking changes can occur, to set user expectations; or,
* Defining a support strategy (e.g. support both flags for some period of time, deprecating the old one, etc)

Prior to the linked pull request, the code looked like this:

https://github.com/GoogleCloudPlatform/gke-autoneg-controller/blob/05c4b1cf9de73dfc33bbec9eb7f9adbe2f09064a/main.go#L57-L63

Afterwards, it now looks like this:

https://github.com/GoogleCloudPlatform/gke-autoneg-controller/blob/b8b9a87c65f3bfc07aebc60649b4f5c4af7d3230/main.go#L62-L70

Overall, the goal is just to ensure that users and developers have aligned expectations. Perhaps users should not expect stability given that we are pre-1.0. In this case, users upgrading from 0.9.8 to 0.9.9 will have to update their deployment manifests.

**Comment by rosmo** [comment]
So, 1.0 is out. We will be adding new features (such as the continuous reconciliation), but next release will be 2.0. Any bugfixes will be ported back to 1.0. Hope this is sufficient?

**Comment by rosmo** [comment]
I think we're option for a more conservative approach, next would be 1.1.0. Any bugfixes would be 1.0.x.
